# Root to save
#root: C:/Users/optiva/Desktop/TFG/2020-tfg-alvaro-martin/Datashet
root: /Users/Martin/Desktop/

# Type of element to generate
to_generate: f #frame('f')

# If toGenerate = 'n'; Function type
func_type: linear #linear

# If toGenerate = 'v' or 'f'; Motion type
motion_type: linear # linear, parabolic, sinusoidal

# If toGenerate = 'f'; Height, width, object
height: 80
width: 120
object: point # point, circle
obj_color: 255 # For b/w: 255; For color: [0, 255, 0]
dof: var # fix, var, (var_1), (var_2) Ordenados por orden 1,2,3,4..

circle_parameters:
  radius: 5

# Number of samples
n_samples: 5000

# Number of know points (x values)
n_points: 69

# Gap between last know and to predict samples
gap: 30

# Noise
noise:
  flag: False #True to add noise to the samples
  mean: 0
  stand_deviation: 50

# Separate train, test and validation
split:
  flag: True #True to separate
  fraction_test: 0.1
  fraction_validation: 0.1
