# Test dataset path
data_path: /Users/Martin/Desktop/Generator_10/Frames_dataset/linear_point_255_fix_6000_80_120/linear_10_[None]_test

# Model path
model_path: /Users/Martin/Desktop/TFG/Proyecto Github/2020-tfg-alvaro-martin/Models/REC/Frames_dataset/linear_point_255_fix_6000_80_120_Modeled/convLSTM/10_False_tanh_mean_squared_error_10.h5
