# Version
version: 1

# Complexity: simple, complex, convLSTM, complex_convLSTM
complexity: complex

# Root to save the model
root:  /Users/Martin/Desktop/TFG/Proyecto Github/2020-tfg-alvaro-martin/Generator & Train_Test/Models/
#root:  C:/Users/optiva/Desktop/TFG/2020-tfg-alvaro-martin/Generator & Train_Test/Models/

# Type of the net to train (NoRec, Rec)
net_type: Rec

# Activation function
activation: relu
modeled_activation: tanh

# Loss function
raw_frame_loss: categorical_crossentropy
modeled_frame_loss: mean_squared_error

# Dropout options
dropout:
  flag: False
  percentage: 0.2

# Epochs
n_epochs: 5000

# Batch size
batch_size: 10

# Patience
patience: 15

# Data
data_dir: /Users/Martin/Desktop/_30/Frames_dataset/linear_var_100_80_120_PRUEBA/linear_30_[None]_
#data_dir: /Users/Martin/Desktop/Generator_10/Frames_dataset/parabolic_point_255_var_1_6000_80_120/parabolic_10_[None]_
#data_dir: /Users/Martin/Desktop/Generator_10/Frames_dataset/sinusoidal_point_255_fix_1000_80_120/sinusoidal_10_[None]_

# WINDOWS ······················································

# Data
#data_dir: C:/Users/optiva/Desktop/TFG/2020-tfg-alvaro-martin/Generator & Train_Test/Datashet_10/Frames_dataset/linear_point_255_var_1_20000_80_120/linear_10_[None]_
#data_dir: C:/Users/optiva/Desktop/TFG/2020-tfg-alvaro-martin/Generator & Train_Test/Datashet_10/Frames_dataset/parabolic_point_255_var_1_6000_80_120/parabolic_10_[None]_
#data_dir: C:/Users/optiva/Desktop/TFG/2020-tfg-alvaro-martin/Generator & Train_Test/Datashet_10/Frames_dataset/sinusoidal_point_255_fix_1000_80_120/sinusoidal_10_[None]_

batch_data: True #True or False
data_model: modeled #raw or modeled
gauss_pixel: False
